/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asistencia.cliente;

/**
 *
 * @author Renato
 */
public class jfAsistenciaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form jfAsistenciaPrincipal
     */
    public jfAsistenciaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jmbMenuPrincipal = new javax.swing.JMenuBar();
        jmControlPersonal = new javax.swing.JMenu();
        jmAsistencia = new javax.swing.JMenu();
        jmiAdministraAsistencia = new javax.swing.JMenuItem();
        jmiConsultaAsistencia = new javax.swing.JMenuItem();
        jmPapeleta = new javax.swing.JMenu();
        jmiRegistrar = new javax.swing.JMenuItem();
        jmiAdministrar = new javax.swing.JMenuItem();
        jmiConsultar = new javax.swing.JMenuItem();
        jmiSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jmControlPersonal.setText("Control Personal");
        jmControlPersonal.setToolTipText("Operaciones de Control de Personal");

        jmAsistencia.setText("Asistencia Diaria");
        jmAsistencia.setToolTipText("Operaciones de Asistencia diaria");

        jmiAdministraAsistencia.setText("Administrar");
        jmiAdministraAsistencia.setToolTipText("Administrar las asistencias diarias");
        jmAsistencia.add(jmiAdministraAsistencia);

        jmiConsultaAsistencia.setText("Consultar");
        jmiConsultaAsistencia.setToolTipText("Consultar las asistencias diarias");
        jmAsistencia.add(jmiConsultaAsistencia);

        jmControlPersonal.add(jmAsistencia);

        jmPapeleta.setText("Papeleta");
        jmPapeleta.setToolTipText("Operaciones de Papeletas de trabajadores");

        jmiRegistrar.setText("Registrar");
        jmiRegistrar.setToolTipText("Registrar Papeletas ");
        jmPapeleta.add(jmiRegistrar);

        jmiAdministrar.setText("Administrar");
        jmiAdministrar.setToolTipText("Administrar Papeletas");
        jmPapeleta.add(jmiAdministrar);

        jmiConsultar.setText("Consultar");
        jmiConsultar.setToolTipText("Consultar Papeletas");
        jmPapeleta.add(jmiConsultar);

        jmControlPersonal.add(jmPapeleta);

        jmiSalir.setText("Salir");
        jmiSalir.setToolTipText("Salir del Control del personal");
        jmControlPersonal.add(jmiSalir);

        jmbMenuPrincipal.add(jmControlPersonal);

        setJMenuBar(jmbMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfAsistenciaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfAsistenciaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfAsistenciaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfAsistenciaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfAsistenciaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jmAsistencia;
    private javax.swing.JMenu jmControlPersonal;
    private javax.swing.JMenu jmPapeleta;
    private javax.swing.JMenuBar jmbMenuPrincipal;
    private javax.swing.JMenuItem jmiAdministraAsistencia;
    private javax.swing.JMenuItem jmiAdministrar;
    private javax.swing.JMenuItem jmiConsultaAsistencia;
    private javax.swing.JMenuItem jmiConsultar;
    private javax.swing.JMenuItem jmiRegistrar;
    private javax.swing.JMenuItem jmiSalir;
    // End of variables declaration//GEN-END:variables
}
